{{- if eq .Values.populateWithSampleData.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: import-demo-data-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  openSslPassword: MDFaUlBGdU9OMFBNb25P
---
apiVersion: batch/v1
kind: Job
metadata:
  name: import-es-demo-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
        - name: import-es-demo-data
          image: "{{ .Values.opengovernance.docker.registry }}/demo-importer:{{ .Values.opengovernance.docker.tags.demoImport }}"
          command: ["/demo-importer-worker"]
          env:
{{- include "elastic.envs" . | indent 12 }}
            - name: POSTGRESQL_USERNAME
              value: "{{ include "postgres.masterUser" . }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ include "postgres.masterPassword" . }}"
            - name: POSTGRESQL_HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: POSTGRESQL_PORT
              value: "{{ include "postgres.port" . }}"
            - name: DEMO_DATA_S3_URL
              value: "https://opengovernance.nyc3.cdn.digitaloceanspaces.com/demo-data/v1.0/demo_data.tar.gz.enc"
            - name: OPENSSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: import-demo-data-secret
                  key: openSslPassword
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: import-psql-demo-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
        - name: import-psql-demo-data
          image: "{{ .Values.opengovernance.docker.registry }}/import-data-script:{{ .Values.opengovernance.docker.tags.psqlImport }}"
          command: ["/bin/bash", "-c", "/usr/local/bin/import_psql_data.sh"]
          env:
{{- include "elastic.envs" . | indent 12 }}
            - name: POSTGRESQL_USERNAME
              value: "{{ include "postgres.masterUser" . }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ include "postgres.masterPassword" . }}"
            - name: POSTGRESQL_HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: POSTGRESQL_PORT
              value: "{{ include "postgres.port" . }}"
            - name: DEMO_DATA_GIT_URL
              value: "https://github.com/kaytu-io/demo-data"
            - name: DEMO_DATA_S3_URL
              value: "https://opengovernance.nyc3.cdn.digitaloceanspaces.com/demo-data/v1.0/demo_data.tar.gz.enc"
            - name: OPENSSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: import-demo-data-secret
                  key: openSslPassword
      restartPolicy: Never
  backoffLimit: 4
{{- end }}